import { useEffect, useState } from "react";
import { createAssignments, listAdminQuizzes, listUsers, type AdminQuiz, type AdminUser } from "../../api/admin";

export function AssignmentsPanel() {
  const [users, setUsers] = useState<AdminUser[]>([]); const [quizzes, setQuizzes] = useState<AdminQuiz[]>([]);
  const [quizId, setQuizId] = useState(""); const [selected, setSelected] = useState<string[]>([]); const [search, setSearch] = useState(""); const [minutes, setMinutes] = useState(30); const [dueAt, setDueAt] = useState(""); const [message, setMessage] = useState<string | null>(null);
  useEffect(() => { Promise.all([listUsers(), listAdminQuizzes()]).then(([u, q]) => { setUsers(u.filter(x => x.role === "EMPLOYEE")); setQuizzes(q.filter(x => x.isActive)); }).catch(() => setMessage("Couldn't load assignment data.")); }, []);
  async function assign() { try { await createAssignments({ quizId, employeeIds: selected, durationMinutes: minutes, dueAt: dueAt || null, enabled: true }); setMessage(`Assessment enabled for ${selected.length} employee(s).`); setSelected([]); } catch (err: any) { setMessage(err?.response?.data?.error || "Couldn't create assignments."); } }
  const available = users.filter(u => !selected.includes(u.id) && `${u.name} ${u.email} ${u.platform}`.toLowerCase().includes(search.toLowerCase()));
  return <section><h2 className="font-display text-lg font-semibold text-text">Assign assessment</h2><p className="mt-1 font-body text-sm text-muted">Select one or many employees. They can start only after you enable this assignment.</p><div className="mt-5 rounded-lg border border-panel-line bg-panel p-5"><label className="block font-body text-sm text-text">Assessment<select className="mt-2 w-full rounded-md border border-panel-line bg-ink p-2 text-text" value={quizId} onChange={e => setQuizId(e.target.value)}><option value="">Select assessment</option>{quizzes.map(q => <option key={q.id} value={q.id}>{q.title}</option>)}</select></label><label className="mt-4 block font-body text-sm text-text">Find employee<input className="mt-2 w-full rounded border border-panel-line bg-ink p-2 text-text" placeholder="Search by name, email, or platform" value={search} onChange={e => setSearch(e.target.value)}/></label><select className="mt-2 w-full rounded border border-panel-line bg-ink p-2 text-text" value="" onChange={e => { if (e.target.value) { setSelected(s => [...s, e.target.value]); setSearch(""); } }}><option value="">Select employee to add</option>{available.map(u => <option key={u.id} value={u.id}>{u.name} — {u.platform} · {u.level}</option>)}</select>{selected.length > 0 && <div className="mt-3 flex flex-wrap gap-2">{selected.map(id => { const u = users.find(x => x.id === id); return <button key={id} onClick={() => setSelected(s => s.filter(x => x !== id))} className="rounded-full border border-accent px-3 py-1 font-body text-xs text-accent">{u?.name} ×</button>; })}</div>}<div className="mt-5 flex flex-wrap gap-4"><label className="font-body text-sm text-text">Time (minutes)<input className="ml-2 w-20 rounded border border-panel-line bg-ink p-2 text-text" type="number" min="1" max="480" value={minutes} onChange={e => setMinutes(Number(e.target.value))}/></label><label className="font-body text-sm text-text">Due date (optional)<input className="ml-2 rounded border border-panel-line bg-ink p-2 text-text" type="datetime-local" value={dueAt} onChange={e => setDueAt(e.target.value)}/></label></div>{message && <p className="mt-4 font-body text-sm text-accent">{message}</p>}<button disabled={!quizId || selected.length === 0} onClick={assign} className="mt-5 rounded-md bg-accent px-4 py-2 font-body text-sm font-semibold text-ink disabled:opacity-40">Enable for selected employees</button></div></section>;
}
