import { useEffect, useState } from "react";
import { getTeam, listAvailableQuizzes, listMyRequests, requestAssessment, type ManagerQuiz, type ManagerRequest, type TeamMember } from "../../api/manager";

export function RequestPanel() {
  const [team, setTeam] = useState<TeamMember[]>([]); const [quizzes, setQuizzes] = useState<ManagerQuiz[]>([]); const [requests, setRequests] = useState<ManagerRequest[]>([]);
  const [quizId, setQuizId] = useState(""); const [employeeIds, setEmployeeIds] = useState<string[]>([]); const [search, setSearch] = useState(""); const [note, setNote] = useState(""); const [message, setMessage] = useState<string | null>(null);
  const load = () => Promise.all([getTeam(), listAvailableQuizzes(), listMyRequests()]).then(([t, q, r]) => { setTeam(t); setQuizzes(q); setRequests(r); }).catch(() => setMessage("Couldn't load request options."));
  useEffect(() => { void load(); }, []);
  async function submit() { try { await requestAssessment({ quizId, employeeIds, message: note }); setMessage("Request sent to the admin."); setEmployeeIds([]); setNote(""); load(); } catch (err: any) { setMessage(err?.response?.data?.error || "Couldn't send request."); } }
  const available = team.filter(u => !employeeIds.includes(u.id) && `${u.name} ${u.email} ${u.platform}`.toLowerCase().includes(search.toLowerCase()));
  return <section><h2 className="font-display text-lg font-semibold text-text">Request an assessment</h2><p className="mt-1 font-body text-sm text-muted">Select one or more people from your team. The admin must approve and enable it before anyone can start.</p><div className="mt-5 rounded-lg border border-panel-line bg-panel p-5"><label className="block font-body text-sm text-text">Assessment<select className="mt-2 w-full rounded border border-panel-line bg-ink p-2 text-text" value={quizId} onChange={e => setQuizId(e.target.value)}><option value="">Select assessment</option>{quizzes.map(q => <option key={q.id} value={q.id}>{q.title}</option>)}</select></label><label className="mt-4 block font-body text-sm text-text">Find employee<input className="mt-2 w-full rounded border border-panel-line bg-ink p-2 text-text" placeholder="Search your team" value={search} onChange={e => setSearch(e.target.value)}/></label><select className="mt-2 w-full rounded border border-panel-line bg-ink p-2 text-text" value="" onChange={e => { if (e.target.value) { setEmployeeIds(ids => [...ids, e.target.value]); setSearch(""); } }}><option value="">Select employee to add</option>{available.map(u => <option key={u.id} value={u.id}>{u.name} — {u.platform} · {u.level}</option>)}</select>{employeeIds.length > 0 && <div className="mt-3 flex flex-wrap gap-2">{employeeIds.map(id => { const u = team.find(x => x.id === id); return <button key={id} onClick={() => setEmployeeIds(ids => ids.filter(x => x !== id))} className="rounded-full border border-accent px-3 py-1 font-body text-xs text-accent">{u?.name} ×</button>; })}</div>}<textarea className="mt-4 w-full rounded border border-panel-line bg-ink p-2 text-sm text-text" placeholder="Optional note for the admin" value={note} onChange={e => setNote(e.target.value)}/>{message && <p className="mt-3 font-body text-sm text-accent">{message}</p>}<button disabled={!quizId || employeeIds.length === 0} onClick={submit} className="mt-4 rounded bg-accent px-4 py-2 text-sm font-semibold text-ink disabled:opacity-40">Send request</button></div><h3 className="mt-8 font-display text-base font-semibold text-text">Request history</h3><div className="mt-3 space-y-2">{requests.map(r => <p key={r.id} className="rounded border border-panel-line bg-panel p-3 font-body text-sm text-text">{r.quiz.title} — {r.recipients.map(x => x.employee.name).join(", ")} <span className="text-muted">({r.status})</span></p>)}</div></section>;
}
